from app.models import db, Favorite


def seed_favorites():

    favorite1 = Favorite(user_id=1, listing_id=1)
    favorite2 = Favorite(user_id=2, listing_id=2)
    favorite3 = Favorite(user_id=3, listing_id=23)
    favorite4 = Favorite(user_id=4, listing_id=4)
    favorite5 = Favorite(user_id=5, listing_id=5)
    favorite6 = Favorite(user_id=6, listing_id=6)
    favorite7 = Favorite(user_id=7, listing_id=7)
    favorite8 = Favorite(user_id=8, listing_id=8)
    favorite9 = Favorite(user_id=9, listing_id=9)
    favorite10 = Favorite(user_id=10, listing_id=10)
    favorite11 = Favorite(user_id=11, listing_id=11)
    favorite12 = Favorite(user_id=12, listing_id=12)
    favorite13 = Favorite(user_id=13, listing_id=13)
    favorite14 = Favorite(user_id=14, listing_id=14)
    favorite15 = Favorite(user_id=15, listing_id=15)
    favorite16 = Favorite(user_id=16, listing_id=16)
    favorite17 = Favorite(user_id=17, listing_id=17)
    favorite18 = Favorite(user_id=18, listing_id=18)
    favorite19 = Favorite(user_id=19, listing_id=19)
    favorite20 = Favorite(user_id=20, listing_id=20)
    favorite21 = Favorite(user_id=20, listing_id=21)
    favorite22 = Favorite(user_id=19, listing_id=22)
    favorite23 = Favorite(user_id=18, listing_id=23)
    favorite24 = Favorite(user_id=17, listing_id=24)
    favorite25 = Favorite(user_id=16, listing_id=25)
    favorite26 = Favorite(user_id=15, listing_id=26)
    favorite27 = Favorite(user_id=14, listing_id=27)
    favorite28 = Favorite(user_id=13, listing_id=28)
    favorite29 = Favorite(user_id=12, listing_id=29)
    favorite30 = Favorite(user_id=11, listing_id=30)
    favorite31 = Favorite(user_id=10, listing_id=31)
    favorite32 = Favorite(user_id=9, listing_id=32)
    favorite33 = Favorite(user_id=8, listing_id=33)
    favorite34 = Favorite(user_id=7, listing_id=34)
    favorite35 = Favorite(user_id=6, listing_id=35)
    favorite36 = Favorite(user_id=5, listing_id=36)
    favorite37 = Favorite(user_id=4, listing_id=37)
    favorite38 = Favorite(user_id=3, listing_id=38)
    favorite39 = Favorite(user_id=2, listing_id=39)
    favorite40 = Favorite(user_id=1, listing_id=40)
    favorite41 = Favorite(user_id=1, listing_id=41)
    favorite42 = Favorite(user_id=2, listing_id=42)
    favorite43 = Favorite(user_id=3, listing_id=43)
    favorite44 = Favorite(user_id=4, listing_id=44)
    favorite45 = Favorite(user_id=5, listing_id=45)
    favorite46 = Favorite(user_id=6, listing_id=36)
    favorite47 = Favorite(user_id=7, listing_id=47)
    favorite48 = Favorite(user_id=8, listing_id=48)
    favorite49 = Favorite(user_id=9, listing_id=49)
    favorite50 = Favorite(user_id=10, listing_id=50)
    favorite51 = Favorite(user_id=1, listing_id=11)
    favorite52 = Favorite(user_id=2, listing_id=12)
    favorite53 = Favorite(user_id=3, listing_id=13)
    favorite54 = Favorite(user_id=4, listing_id=14)
    favorite55 = Favorite(user_id=5, listing_id=15)
    favorite56 = Favorite(user_id=6, listing_id=16)
    favorite57 = Favorite(user_id=7, listing_id=17)
    favorite58 = Favorite(user_id=8, listing_id=18)
    favorite59 = Favorite(user_id=9, listing_id=19)
    favorite60 = Favorite(user_id=10, listing_id=11)
    favorite61 = Favorite(user_id=11, listing_id=12)
    favorite62 = Favorite(user_id=12, listing_id=13)
    favorite63 = Favorite(user_id=13, listing_id=14)
    favorite64 = Favorite(user_id=14, listing_id=15)
    favorite65 = Favorite(user_id=15, listing_id=16)
    favorite66 = Favorite(user_id=16, listing_id=17)
    favorite67 = Favorite(user_id=17, listing_id=18)
    favorite68 = Favorite(user_id=18, listing_id=19)
    favorite69 = Favorite(user_id=19, listing_id=9)
    favorite70 = Favorite(user_id=20, listing_id=2)
    favorite71 = Favorite(user_id=20, listing_id=1)
    favorite72 = Favorite(user_id=19, listing_id=12)
    favorite73 = Favorite(user_id=18, listing_id=3)
    favorite74 = Favorite(user_id=17, listing_id=4)
    favorite75 = Favorite(user_id=16, listing_id=5)
    favorite76 = Favorite(user_id=15, listing_id=6)
    favorite77 = Favorite(user_id=14, listing_id=7)
    favorite78 = Favorite(user_id=13, listing_id=8)
    favorite79 = Favorite(user_id=12, listing_id=9)
    favorite80 = Favorite(user_id=11, listing_id=40)
    favorite81 = Favorite(user_id=10, listing_id=1)
    favorite82 = Favorite(user_id=9, listing_id=2)
    favorite83 = Favorite(user_id=8, listing_id=3)
    favorite84 = Favorite(user_id=7, listing_id=4)
    favorite85 = Favorite(user_id=6, listing_id=5)
    favorite86 = Favorite(user_id=5, listing_id=6)
    favorite87 = Favorite(user_id=4, listing_id=7)
    favorite88 = Favorite(user_id=3, listing_id=8)
    favorite89 = Favorite(user_id=2, listing_id=29)
    favorite90 = Favorite(user_id=1, listing_id=30)
    favorite91 = Favorite(user_id=1, listing_id=61)
    favorite92 = Favorite(user_id=2, listing_id=22)
    favorite93 = Favorite(user_id=3, listing_id=3)
    favorite94 = Favorite(user_id=4, listing_id=11)
    favorite95 = Favorite(user_id=5, listing_id=25)
    favorite96 = Favorite(user_id=6, listing_id=46)
    favorite97 = Favorite(user_id=7, listing_id=29)
    favorite98 = Favorite(user_id=8, listing_id=14)
    favorite99 = Favorite(user_id=9, listing_id=16)
    favorite100 = Favorite(user_id=10, listing_id=49)

    db.session.add(favorite1)
    db.session.add(favorite2)
    db.session.add(favorite3)
    db.session.add(favorite4)
    db.session.add(favorite5)
    db.session.add(favorite6)
    db.session.add(favorite7)
    db.session.add(favorite8)
    db.session.add(favorite9)
    db.session.add(favorite10)
    db.session.add(favorite11)
    db.session.add(favorite12)
    db.session.add(favorite13)
    db.session.add(favorite14)
    db.session.add(favorite15)
    db.session.add(favorite16)
    db.session.add(favorite17)
    db.session.add(favorite18)
    db.session.add(favorite19)
    db.session.add(favorite20)
    db.session.add(favorite21)
    db.session.add(favorite22)
    db.session.add(favorite23)
    db.session.add(favorite24)
    db.session.add(favorite25)
    db.session.add(favorite26)
    db.session.add(favorite27)
    db.session.add(favorite28)
    db.session.add(favorite29)
    db.session.add(favorite30)
    db.session.add(favorite31)
    db.session.add(favorite32)
    db.session.add(favorite33)
    db.session.add(favorite34)
    db.session.add(favorite35)
    db.session.add(favorite36)
    db.session.add(favorite37)
    db.session.add(favorite38)
    db.session.add(favorite39)
    db.session.add(favorite40)
    db.session.add(favorite41)
    db.session.add(favorite42)
    db.session.add(favorite43)
    db.session.add(favorite44)
    db.session.add(favorite45)
    db.session.add(favorite46)
    db.session.add(favorite47)
    db.session.add(favorite48)
    db.session.add(favorite49)
    db.session.add(favorite50)
    db.session.add(favorite51)
    db.session.add(favorite52)
    db.session.add(favorite53)
    db.session.add(favorite54)
    db.session.add(favorite55)
    db.session.add(favorite56)
    db.session.add(favorite57)
    db.session.add(favorite58)
    db.session.add(favorite59)
    db.session.add(favorite60)
    db.session.add(favorite61)
    db.session.add(favorite62)
    db.session.add(favorite63)
    db.session.add(favorite64)
    db.session.add(favorite65)
    db.session.add(favorite66)
    db.session.add(favorite67)
    db.session.add(favorite68)
    db.session.add(favorite69)
    db.session.add(favorite70)
    db.session.add(favorite71)
    db.session.add(favorite72)
    db.session.add(favorite73)
    db.session.add(favorite74)
    db.session.add(favorite75)
    db.session.add(favorite76)
    db.session.add(favorite77)
    db.session.add(favorite78)
    db.session.add(favorite79)
    db.session.add(favorite80)
    db.session.add(favorite81)
    db.session.add(favorite82)
    db.session.add(favorite83)
    db.session.add(favorite84)
    db.session.add(favorite85)
    db.session.add(favorite86)
    db.session.add(favorite87)
    db.session.add(favorite88)
    db.session.add(favorite89)
    db.session.add(favorite90)
    db.session.add(favorite91)
    db.session.add(favorite92)
    db.session.add(favorite93)
    db.session.add(favorite94)
    db.session.add(favorite95)
    db.session.add(favorite96)
    db.session.add(favorite97)
    db.session.add(favorite98)
    db.session.add(favorite99)
    db.session.add(favorite100)

    db.session.commit()


def undo_favorites():
    db.session.execute('TRUNCATE favorites;')
    db.session.commit()
